/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

import org.junit.Assert;

public class ProjectWithKarma2 {
	 @Test 
	    public void testSomeLibraryMethod() {
	    	System.out.println("ProjectWithKarma2");
//	    	Assert.fail();
	    }
}
