/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

import org.junit.Assert;

public class ProjectWithKarma1 {
	
    @Test 
    public void testSomeLibraryMethod() {
    	System.out.println("ProjectWithKarma1xxx");
//    	Assert.fail();
    }
}
